### ISSUE TITLE
Ghidra 11.0.1

### ISSUE THREAD

**Issue by NTxC** [lab313ru/ghidra_sega_ldr#7]
The extension throws the following error if used in Ghidra 11.0.1:

`(TaskBuilderTask) Task Error: Import File - Uncaught Exception: java.lang.NoSuchMethodError: 'void ghidra.app.util.bin.BinaryReader.setPointerIndex(int)' java.lang.NoSuchMethodError: 'void ghidra.app.util.bin.BinaryReader.setPointerIndex(int)' at sega.VectorsTable.(VectorsTable.java:34)`

Could you please update the extension for use with Ghidra 11.0.1?

**Comment by NTxC** [comment]
I already compiled it myself. Here's the extension archive supported by Ghidra 11.0.1.

[ghidra_11.0.1_PUBLIC_20240205_ghidra_sega_ldr-master.zip](https://github.com/lab313ru/ghidra_sega_ldr/files/14172855/ghidra_11.0.1_PUBLIC_20240205_ghidra_sega_ldr-master.zip)

**Comment by charlescochran** [comment]
Yes, getting the same error. Thanks for providing `11.0.1` version! It's working for me. You should open a PR to add this as a new release.
@lab313ru

**Comment by lab313ru** [comment]
Updated.
